# Generated by Django 3.1.7 on 2021-03-08 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change_password', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('is_blocked', models.SmallIntegerField(default=0, verbose_name='Bloqueo de cuenta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfiluser', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
