# Generated by Django 3.1.7 on 2021-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('segundo_nombre', models.CharField(max_length=50, verbose_name='Segundo nombre')),
                ('tercer_nombre', models.CharField(max_length=50, verbose_name='Tercer Nombre')),
                ('cuarto_nombre', models.CharField(max_length=50, verbose_name='Cuarto Nombre')),
                ('apellido_de_casada', models.CharField(max_length=50, null=True, verbose_name='Apellido de casada')),
                ('dpi_cliente', models.CharField(max_length=50, verbose_name='DPI')),
                ('profesion', models.CharField(max_length=50, verbose_name='Profesion')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('telefono_casa', models.CharField(max_length=50, verbose_name='Telefono de casa')),
                ('celular', models.CharField(max_length=50, verbose_name='Telefono celular')),
                ('nit', models.CharField(max_length=30, verbose_name='Numero de NIT')),
                ('estado_civil', models.CharField(choices=[(0, 'Soltero'), (1, 'Casado')], default=0, max_length=25, verbose_name='Estado Civil')),
                ('conyugue', models.CharField(max_length=100, verbose_name='Conyuge')),
                ('condicion_vivienda', models.CharField(choices=[(0, 'Propia'), (1, 'Alquilada'), (2, 'Usufructo'), (3, 'Familiar'), (4, 'Adeuda'), (5, 'Prestada')], default=0, max_length=25, verbose_name='Condicion de vivienda')),
                ('correo_electronico', models.CharField(max_length=25, verbose_name='Correo electronico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
