# Generated by Django 3.1.7 on 2021-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actividad_economica_empresa_prd',
            field=models.CharField(default=None, max_length=50, verbose_name='Actividad economica de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_de_la_empresa_prd',
            field=models.CharField(default=None, max_length=50, verbose_name='Direccion de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_ep',
            field=models.DateField(default=None, max_length=25, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_prd',
            field=models.DateField(default=None, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit_ep',
            field=models.CharField(default=None, max_length=25, verbose_name='NIT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_de_la_empresa_ep',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_de_la_empresa_prd',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre de la empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='primera_referencia_f',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='primera_referencia_p',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='puesto_de_trabajo_prd',
            field=models.CharField(default=None, max_length=50, verbose_name='Puesto de trabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='segunda_referencia_f',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='segunda_referencia_p',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_ep',
            field=models.CharField(default=None, max_length=25, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_prd',
            field=models.CharField(default=None, max_length=25, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_primera_referencia_f',
            field=models.CharField(default=None, max_length=50, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_primera_referencia_p',
            field=models.CharField(default=None, max_length=50, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_segunda_referencia_f',
            field=models.CharField(default=None, max_length=50, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_segunda_referencia_p',
            field=models.CharField(default=None, max_length=50, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
