# Generated by Django 3.1.7 on 2021-04-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210316_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='primer_nombre',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
    ]
