# Generated by Django 3.1.7 on 2021-04-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20210401_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuarto_nombre',
            field=models.CharField(max_length=50, verbose_name='Cuarto nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primer_nombre',
            field=models.CharField(max_length=50, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tercer_nombre',
            field=models.CharField(max_length=50, verbose_name='Tercer nombre'),
        ),
    ]
