# Generated by Django 3.1.7 on 2021-04-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20210402_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
