# Generated by Django 3.1.7 on 2021-03-16 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('monto', models.FloatField(verbose_name='Monto de caja')),
                ('updated_at', models.DateTimeField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
