# Generated by Django 3.1.7 on 2021-03-16 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_auto_20210316_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('plazo', models.CharField(choices=[(0, 'Diario'), (1, 'Semanal'), (2, 'Mensual')], default=2, max_length=25, verbose_name='Plazo')),
                ('forma_de_pago', models.CharField(max_length=25, verbose_name='Forma de pago')),
                ('taza_de_interes', models.FloatField(verbose_name='Taza de interes')),
                ('tipo_garantia', models.CharField(max_length=50, verbose_name='Tipo de garantia')),
                ('descripcion_garantia', models.CharField(max_length=25, verbose_name='Descripcion de la garantia')),
                ('marca', models.CharField(max_length=25, verbose_name='Marca')),
                ('numero_serie', models.CharField(max_length=25, verbose_name='Numero de serie')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('cic', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('cliente_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente Credito')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
