# Generated by Django 3.1.7 on 2021-03-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210316_1543'),
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='cliente_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Credito a nombre de '),
        ),
        migrations.AlterField(
            model_name='credito',
            name='plazo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='mensual', max_length=25, verbose_name='Plazo'),
        ),
    ]
