# Generated by Django 3.1.7 on 2021-04-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_auto_20210316_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
