# Generated by Django 3.1.7 on 2021-04-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_auto_20210402_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='plazo',
            field=models.CharField(choices=[(0, 'Diario'), (1, 'Semanal'), (2, 'Quincenal'), (3, 'Mensual')], default=0, max_length=25, verbose_name='Plazo'),
        ),
    ]
