# Generated by Django 3.1.7 on 2021-04-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_auto_20210407_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='plazo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='diario', max_length=25, verbose_name='Plazo'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='taza_de_interes',
            field=models.FloatField(default=15, verbose_name='Taza de interes'),
        ),
    ]
