# Generated by Django 3.1.7 on 2021-04-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_auto_20210414_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cuota_total_diaria',
            field=models.FloatField(default=0, verbose_name='Cuota total diaria'),
        ),
    ]
