# Generated by Django 3.1.7 on 2021-04-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_auto_20210418_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cuota_interes_diaria',
            field=models.FloatField(default=0, verbose_name='Cuota de interes diaria'),
        ),
    ]
